var annotated_dup =
[
    [ "AddInstr", "structAddInstr.html", "structAddInstr" ],
    [ "btree_header", "structbtree__header.html", null ],
    [ "btree_page", "structbtree__page.html", null ],
    [ "charray", "structcharray.html", "structcharray" ],
    [ "condition", "structcondition.html", "structcondition" ],
    [ "CrtInstr", "structCrtInstr.html", "structCrtInstr" ],
    [ "Cursor", "structCursor.html", "structCursor" ],
    [ "data", "structdata.html", null ],
    [ "dataarray", "structdataarray.html", null ],
    [ "dbtree", "structdbtree.html", null ],
    [ "idxdata", "structidxdata.html", null ],
    [ "idxdataaray", "structidxdataaray.html", null ],
    [ "idxkey_value", "structidxkey__value.html", null ],
    [ "idxnode", "structidxnode.html", null ],
    [ "indexbtree", "structindexbtree.html", null ],
    [ "indexbtreearray", "structindexbtreearray.html", null ],
    [ "instr", "structinstr.html", null ],
    [ "InstrArray", "structInstrArray.html", null ],
    [ "key_value", "structkey__value.html", null ],
    [ "linked_overflow", "structlinked__overflow.html", null ],
    [ "node", "structnode.html", null ],
    [ "overflow_data", "structoverflow__data.html", null ],
    [ "overflow_header", "structoverflow__header.html", null ],
    [ "parsingData", "structparsingData.html", null ],
    [ "record", "structrecord.html", null ],
    [ "SelInstr", "structSelInstr.html", "structSelInstr" ],
    [ "singlepair", "structsinglepair.html", null ],
    [ "ti_cell", "structti__cell.html", null ],
    [ "tl_cell", "structtl__cell.html", null ],
    [ "tl_cell_header", "structtl__cell__header.html", null ],
    [ "yacdb", "structyacdb.html", null ],
    [ "yacdb_header", "structyacdb__header.html", null ]
];